game:
  arch: win64
  exe: drive_c/project_06/Sonic the Hedgehog.exe
  prefix: /mnt/gs1/Games/project-06
game_slug: project-06
name: Project 06
requires: null
script:
  files:
  - gamezip: N/A:Please select the Project 06 zip file
  game:
    arch: win64
    exe: drive_c/project_06/Sonic the Hedgehog.exe
    prefix: $GAMEDIR
  installer:
  - task:
      arch: win64
      prefix: /mnt/gs1/Games/project-06
      wine_path: /home/gfernandez/.local/share/lutris/runners/wine/Proton 8.0/bin/wine
  - extract:
      dst: $GAMEDIR/drive_c/project_06
      src: gamezip
  system:
    env:
      DXVK_HUD: compiler
      DXVK_STATE_CACHE_PATH: $GAMEDIR
  wine:
    dxvk: true
    esync: true
slug: project-06-standalone
system:
  env:
    DXVK_HUD: compiler
    DXVK_STATE_CACHE_PATH: /mnt/gs1/Games/project-06
variables: {}
version: Standalone
wine:
  dxvk: true
  esync: true
year: null
